/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FeedPreviewRouteImport } from './routes/feed-preview'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateMediaRouteImport } from './routes/api.generate-media'
import { Route as ApiEnhancePostRouteImport } from './routes/api.enhance-post'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedPreviewRoute = FeedPreviewRouteImport.update({
  id: '/feed-preview',
  path: '/feed-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateMediaRoute = ApiGenerateMediaRouteImport.update({
  id: '/api/generate-media',
  path: '/api/generate-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnhancePostRoute = ApiEnhancePostRouteImport.update({
  id: '/api/enhance-post',
  path: '/api/enhance-post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/feed-preview': typeof FeedPreviewRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/api/generate-media': typeof ApiGenerateMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/feed-preview': typeof FeedPreviewRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/api/generate-media': typeof ApiGenerateMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/feed-preview': typeof FeedPreviewRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/schedule': typeof ScheduleRoute
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/api/generate-media': typeof ApiGenerateMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/dashboard'
    | '/editor'
    | '/feed-preview'
    | '/history'
    | '/login'
    | '/profile'
    | '/schedule'
    | '/api/enhance-post'
    | '/api/generate-media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/dashboard'
    | '/editor'
    | '/feed-preview'
    | '/history'
    | '/login'
    | '/profile'
    | '/schedule'
    | '/api/enhance-post'
    | '/api/generate-media'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/dashboard'
    | '/editor'
    | '/feed-preview'
    | '/history'
    | '/login'
    | '/profile'
    | '/schedule'
    | '/api/enhance-post'
    | '/api/generate-media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  FeedPreviewRoute: typeof FeedPreviewRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ScheduleRoute: typeof ScheduleRoute
  ApiEnhancePostRoute: typeof ApiEnhancePostRoute
  ApiGenerateMediaRoute: typeof ApiGenerateMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed-preview': {
      id: '/feed-preview'
      path: '/feed-preview'
      fullPath: '/feed-preview'
      preLoaderRoute: typeof FeedPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-media': {
      id: '/api/generate-media'
      path: '/api/generate-media'
      fullPath: '/api/generate-media'
      preLoaderRoute: typeof ApiGenerateMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enhance-post': {
      id: '/api/enhance-post'
      path: '/api/enhance-post'
      fullPath: '/api/enhance-post'
      preLoaderRoute: typeof ApiEnhancePostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  FeedPreviewRoute: FeedPreviewRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ScheduleRoute: ScheduleRoute,
  ApiEnhancePostRoute: ApiEnhancePostRoute,
  ApiGenerateMediaRoute: ApiGenerateMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
